version: "2.2"
services:

  api-hello:
    build:
      context: ./py-api-hello
      dockerfile: Dockerfile

  api-hola:
    build:
      context: ./py-api-hola
      dockerfile: Dockerfile

  traefik:
    image: docker.io/traefik:latest
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./traefik/:/etc/traefik/
    depends_on:
      - api-hola
      - api-hello
    links:
      - api-hello:link-api-hello
      - api-hola:link-api-hola

  node-express:
    build:
      context: ./node-express
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - traefik:link-traefik