version: "2.2"
services:

  api-hello:
    build:
      context: ./py-api-hello
      dockerfile: Dockerfile
    ports:
      - 6780:6780

  api-hola:
    build:
      context: ./py-api-hola
      dockerfile: Dockerfile
    ports:
      - 6781:6781

  traefik:
    image: docker.io/traefik:latest
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api-hola
      - api-hello